export default [
  {
    id: 1,
    name: 'Titi',
    description: 'Titi est un chien très affectueux, qui ne demande que des calins et des balades',
    birthday: '12.02.2013',
    arrival_date: '20.01.2020',
    gender: 'male',
    dog_friendly: true,
    cat_friendly: false,
    child_friendly: true,
    additionnal_information: 'Titi a été trouvé au bord d\'une route, il n\'était pas pucé et n\'a jamais été réclamé',
    picture1: 'https://pixabay.com/fr/images/download/dog-4246454_640.jpg?attachment',
    picture2: 'https://pixabay.com/fr/images/download/dog-4250055_640.jpg?attachment',
    picture3: null,
    picture4: null,
    picture5: null,
    created_at: '2020.01.21',
    updated_at: '2020-01-21',
    status: 1,
  },
  {
    id: 2,
    name: 'Mignonne',
    description: 'Migonne est un peu peureuse au début mais très affectueuse par la suite',
    birthday: '12.02.2010',
    arrival_date: '20.10.2019',
    gender: 'femelle',
    dog_friendly: false,
    cat_friendly: true,
    child_friendly: true,
    additionnal_information: 'Mignonne a été trouvée par un particulier dans son jardin',
    picture1: 'https://pixabay.com/fr/images/download/cat-2528935_640.jpg?attachment',
    picture2: 'https://pixabay.com/fr/images/download/cat-2528930_640.jpg?attachment',
    picture3: null,
    picture4: null,
    picture5: null,
    created_at: '2019.10.21',
    updated_at: '2019-10-21',
    status: 1,
  },
  {
    id: 1,
    name: 'Titi',
    description: 'Titi est un chien très affectueux, qui ne demande que des calins et des balades',
    birthday: '12.02.2013',
    arrival_date: '20.01.2020',
    gender: 'male',
    dog_friendly: true,
    cat_friendly: false,
    child_friendly: true,
    additionnal_information: 'Titi a été trouvé au bord d\'une route, il n\'était pas pucé et n\'a jamais été réclamé',
    picture1: 'https://pixabay.com/fr/images/download/dog-4246454_640.jpg?attachment',
    picture2: 'https://pixabay.com/fr/images/download/dog-4250055_640.jpg?attachment',
    picture3: null,
    picture4: null,
    picture5: null,
    created_at: '2020.01.21',
    updated_at: '2020-01-21',
    status: 1,
  },
  {
    id: 1,
    name: 'Titi',
    description: 'Titi est un chien très affectueux, qui ne demande que des calins et des balades',
    birthday: '12.02.2013',
    arrival_date: '20.01.2020',
    gender: 'male',
    dog_friendly: true,
    cat_friendly: false,
    child_friendly: true,
    additionnal_information: 'Titi a été trouvé au bord d\'une route, il n\'était pas pucé et n\'a jamais été réclamé',
    picture1: 'https://pixabay.com/fr/images/download/dog-4246454_640.jpg?attachment',
    picture2: 'https://pixabay.com/fr/images/download/dog-4250055_640.jpg?attachment',
    picture3: null,
    picture4: null,
    picture5: null,
    created_at: '2020.01.21',
    updated_at: '2020-01-21',
    status: 1,
  },
  {
    id: 1,
    name: 'Titi',
    description: 'Titi est un chien très affectueux, qui ne demande que des calins et des balades',
    birthday: '12.02.2013',
    arrival_date: '20.01.2020',
    gender: 'male',
    dog_friendly: true,
    cat_friendly: false,
    child_friendly: true,
    additionnal_information: 'Titi a été trouvé au bord d\'une route, il n\'était pas pucé et n\'a jamais été réclamé',
    picture1: 'https://pixabay.com/fr/images/download/dog-4246454_640.jpg?attachment',
    picture2: 'https://pixabay.com/fr/images/download/dog-4250055_640.jpg?attachment',
    picture3: null,
    picture4: null,
    picture5: null,
    created_at: '2020.01.21',
    updated_at: '2020-01-21',
    status: 1,
  },
  {
    id: 1,
    name: 'Titi',
    description: 'Titi est un chien très affectueux, qui ne demande que des calins et des balades',
    birthday: '12.02.2013',
    arrival_date: '20.01.2020',
    gender: 'male',
    dog_friendly: true,
    cat_friendly: false,
    child_friendly: true,
    additionnal_information: 'Titi a été trouvé au bord d\'une route, il n\'était pas pucé et n\'a jamais été réclamé',
    picture1: 'https://pixabay.com/fr/images/download/dog-4246454_640.jpg?attachment',
    picture2: 'https://pixabay.com/fr/images/download/dog-4250055_640.jpg?attachment',
    picture3: null,
    picture4: null,
    picture5: null,
    created_at: '2020.01.21',
    updated_at: '2020-01-21',
    status: 1,
  },
];
